export { WORK_HOURS_PER_DAY, DEFAULT_PANEL_THICKNESS, DEFAULT_RAIL_WIDTH, DEFAULT_LEG_HEIGHT, DEFAULT_SHELF_FRONT_INSET } from './types'
export type {
  CabinetCategory,
  CabinetDimensions,
  CabinetGeneratorResult,
  CabinetTypeDefinition,
  GeneratedPanel,
  HardwareItem,
  JoineryConfig,
  KitchenBaseParams,
  LaborEstimate,
  PanelEdgePlan,
  PanelRole,
} from './types'
export type { CabinetInstance } from '@/types'

export { CABINET_TYPES, getCabinetType, generateCabinet, scaleCabinetResult, cabinetDisplayName } from './catalog'
export { measureCarcass, evenShelfBottoms, KITCHEN_BASE_JOINERY } from './joinery'
export {
  KITCHEN_BASE_TYPE_ID,
  DEFAULT_KITCHEN_BASE_PARAMS,
  parseKitchenBaseParams,
  generateKitchenBase,
} from './kitchen-base'
export {
  estimateFromPanels,
  estimateFromParts,
  hourlyRateEur,
  laborMinutes,
  laborCostEur,
  cabinetPrice,
  formatEur,
  formatArea,
  formatMinutes,
  laborFromPanels,
} from './estimate'
export type { CabinetPrice } from './estimate'
export {
  SCREW_5X60,
  SCREW_4X16,
  SCREW_4X20,
  SCREW_35X16,
  SHELF_PIN,
  SHELF_PINS_PER_SHELF,
  FASTENERS,
  KITCHEN_BASE_SCREWS_BOTTOM,
  KITCHEN_BASE_SCREWS_RAILS,
  KITCHEN_BASE_SCREWS_TOTAL,
  HINGES_PER_SMALL_DOOR,
  SLIDES_PER_DRAWER,
  SCREWS_4X16_PER_HINGE,
  SCREWS_4X20_PER_HINGE,
  SCREWS_35X16_PER_SLIDE,
  SCREWS_35X16_PER_SLIDE_WING,
  isSoftCloseSlide,
  screws35x16PerSlide,
  SLIDE_KIND_LABEL,
  SLIDE_KIND_SHORT,
  SLIDE_LENGTHS,
  ALL_SLIDE_LENGTHS,
  fastenerUnitPriceEur,
  fastenerLine,
  pricedLine,
  hardwareCostEur,
  hardwareQtyById,
  hardwareCostById,
  parseSlideKind,
  parseSlideLength,
  eligibleSlideLengths,
  defaultSlideLength,
  slideUnitPriceEur,
  slideId,
  slideName,
} from './hardware'
export type { SlideKind } from './hardware'
export {
  DEFAULT_CHIPBOARD_PRICE_EUR,
  DEFAULT_CHIPBOARD_WIDTH,
  DEFAULT_CHIPBOARD_HEIGHT,
  DEFAULT_HARDBOARD_WIDTH,
  DEFAULT_HARDBOARD_HEIGHT,
  DEFAULT_HARDBOARD_PRICE_EUR,
  DEFAULT_HARDBOARD_THICKNESS,
  EDGE_PRICE_MM2_EUR,
  EDGE_PRICE_MM05_EUR,
  CUTTING_MINUTES_PER_SHEET,
  EDGING_MINUTES_PER_SHEET,
  DOOR_CLEARANCE_TOP,
  DOOR_CLEARANCE_BOTTOM,
  DOOR_GAP_X,
  DRAWER_DOOR_GAP,
  DRAWER_RAIL_BELOW_FRONT,
  ROLLER_SLIDE_SIDE_GAP,
  SOFT_SLIDE_SIDE_GAP,
  SOFT_SLIDE_OUTER_RAIL_SHORTEN,
  SOFT_INNER_RAIL_HEIGHT_DROP,
  DOOR_EDGE_BOTH,
  sheetKind,
  partKind,
  normalizeSheet,
  usedBoardCostEur,
  edgeBandingCostEur,
  referenceSheet,
  firstSheetOfKind,
  doorCutSize,
  drawerFrontCutSize,
  doorWithDrawerCutSize,
  drawerBoxRails,
  parseDoorCount,
  boardKindLabel,
  createHardboardSheet,
} from './materials'
export type { BoardKind, DoorCount, DrawerBoxRails } from './materials'
export {
  addCabinetAndLabel,
  updateCabinetAndLabel,
  removeCabinetAndLabel,
  type CabinetState,
} from './apply'
export { createDrawCam, Board, BETWEEN_FACES, SIDE_LEFT_BODY, SIDE_LEFT_TOP, SIDE_RIGHT, BOX_FACES } from './draw-3d'
export type { DrawCam, DrawFaces } from './draw-3d'
export type { CabinetPartColors, CabinetPartColorKey } from './colors'
export {
  DEFAULT_PART_COLORS,
  DEFAULT_WOOD_COLOR,
  DEFAULT_LEG_COLOR,
  DEFAULT_HARDBOARD_COLOR,
  PART_COLOR_FIELDS,
  parsePartColors,
  partFaces,
} from './colors'
