export { WORK_HOURS_PER_DAY, DEFAULT_PANEL_THICKNESS, DEFAULT_RAIL_WIDTH, DEFAULT_LEG_HEIGHT, DEFAULT_SHELF_FRONT_INSET, TOP_EDGE_BAND_MM, FASCIA_SETBACK_MM, frontDoorOverhang, parseKitchenTopStyle, parseBoxTopStyle, kitchenClearInnerH, panelHoleNote, panelHoleFits } from './types'
export type {
  CabinetCategory,
  CabinetDimensions,
  CabinetGeneratorResult,
  CabinetTypeDefinition,
  CabinetTopStyle,
  GeneratedPanel,
  HardwareItem,
  JoineryConfig,
  KitchenBaseParams,
  LaborEstimate,
  PanelEdgePlan,
  PanelHole,
  PanelRole,
} from './types'
export type { CabinetInstance } from '@/types'

export { clothesRailLengthMm, parseInteriorFittings, appendHangingFascias } from './fronts'
export type { InteriorFittings } from './fronts'
export { CABINET_TYPES, getCabinetType, generateCabinet, scaleCabinetResult, cabinetDisplayName } from './catalog'
export { measureCarcass, evenShelfBottoms, evenShelfGap, KITCHEN_BASE_JOINERY, KITCHEN_WALL_JOINERY } from './joinery'
export {
  MAX_FIXED_SHELVES,
  MAX_FIXED_SHELF_SPECS,
  MAX_PARTITIONS,
  MIN_ZONE_CLEAR_MM,
  ZONE_LABELS,
  EMPTY_ZONE_FITTINGS,
  parseFixedShelves,
  parseMovableShelves,
  parseClothesRails,
  evenShelfPlacements,
  parsePartitions,
  parseDoorSpan,
  parseZoneMap,
  parseColumnIndex,
  shelvesForColumn,
  canAddFixedShelfToColumn,
  canAddFixedShelfFull,
  canAddMoreFixedShelves,
  defaultFixedOffsetMm,
  defaultPartitionOffsetMm,
  DEFAULT_CLOTHES_RAIL_FROM_TOP_MM,
  CLOTHES_RAIL_SECTION_MM,
  MAX_CLOTHES_RAILS,
  resolveFixedShelves,
  resolveMovableShelves,
  pinShelfOpenings,
  preferredMiddleGap,
  resolvePartitions,
  cabinetZones,
  cabinetColumns,
  layoutInterior,
  layoutCounts,
  fittingsCountsFromParams,
  zoneFrontBox,
  stackFronts,
  validateZoneFronts,
  allDrawerFrontHeights,
  overlayFrontExtent,
  overlayFrontExtentX,
  zoneHasOverlayFronts,
  consecutiveZoneFrontRuns,
  canCombineAdjacentZoneFronts,
  canCombineZoneFrontRun,
  defaultShelfFaces,
  defaultPartitionFaces,
  measureFixedShelf,
  measurePartition,
  fixedShelfMeasureLabel,
  movableShelfMeasureLabel,
  clothesRailMeasureLabel,
  partitionMeasureLabel,
  partitionOriginCaption,
  columnLabel,
} from './zones'
export type {
  OverlayFrontCovers,
  FixedShelfSpec,
  FixedShelfFrom,
  MovableShelfFrom,
  MovableShelfSpec,
  ResolvedMovableShelf,
  ClothesRailFrom,
  ClothesRailSpec,
  ResolvedClothesRail,
  PartitionSpec,
  PartitionFrom,
  PanelFace,
  SideFace,
  CabinetZoneId,
  CabinetRowId,
  DoorSpan,
  ZoneFittings,
  ResolvedZone,
  InteriorLayout,
} from './zones'
export {
  KITCHEN_BASE_TYPE_ID,
  DEFAULT_KITCHEN_BASE_PARAMS,
  parseKitchenBaseParams,
  generateKitchenBase,
} from './kitchen-base'
export {
  KITCHEN_WALL_TYPE_ID,
  DEFAULT_KITCHEN_WALL_PARAMS,
  DEFAULT_HOOD_DIAMETER_MM,
  DEFAULT_HOOD_RECT_W_MM,
  DEFAULT_HOOD_RECT_D_MM,
  parseKitchenWallParams,
  wallBottomHole,
  wallShelfHole,
  generateKitchenWall,
  kitchenWallType,
} from './kitchen-wall'
export type { KitchenWallParams, HoodShape } from './kitchen-wall'
export {
  estimateFromPanels,
  estimateFromParts,
  hourlyRateEur,
  laborMinutes,
  laborCostEur,
  cabinetPrice,
  formatEur,
  formatArea,
  formatMinutes,
  laborFromPanels,
  isBuyoutDoorPanel,
  groupBuyoutDoors,
  collectBuyoutDoorOrderList,
} from './estimate'
export type { CabinetPrice, BuyoutDoorGroup, BuyoutDoorOrderRow } from './estimate'
export { explainCabinetPrice, explainCabinetsPrice } from './price-breakdown'
export type { PriceBreakdown, PriceBreakdownLine, PriceBreakdownSection } from './price-breakdown'
export {
  SCREW_5X60,
  confirmatCount,
  SCREW_4X16,
  SCREW_4X20,
  SCREW_35X16,
  CLOTHES_RAIL,
  SHELF_PIN,
  SHELF_PINS_PER_SHELF,
  HANDLE_NORMAL,
  HANDLES_PER_DOOR,
  HANDLES_PER_DRAWER,
  FASTENERS,
  KITCHEN_BASE_SCREWS_BOTTOM,
  KITCHEN_BASE_SCREWS_RAILS,
  KITCHEN_BASE_SCREWS_TOTAL,
  HINGES_PER_SMALL_DOOR,
  SLIDES_PER_DRAWER,
  SCREWS_4X16_PER_HINGE,
  SCREWS_4X20_PER_HINGE,
  SCREWS_35X16_PER_SLIDE,
  SCREWS_35X16_PER_SLIDE_WING,
  isSoftCloseSlide,
  screws35x16PerSlide,
  SLIDE_KIND_LABEL,
  SLIDE_KIND_SHORT,
  SLIDE_LENGTHS,
  ALL_SLIDE_LENGTHS,
  fastenerUnitPriceEur,
  fastenerLine,
  pricedLine,
  hardwareCostEur,
  hardwareQtyById,
  hardwareCostById,
  parseSlideKind,
  parseSlideLength,
  eligibleSlideLengths,
  defaultSlideLength,
  slideUnitPriceEur,
  slideId,
  slideName,
} from './hardware'
export type { SlideKind } from './hardware'
export {
  DEFAULT_CHIPBOARD_PRICE_EUR,
  DEFAULT_CHIPBOARD_WIDTH,
  DEFAULT_CHIPBOARD_HEIGHT,
  DEFAULT_HARDBOARD_WIDTH,
  DEFAULT_HARDBOARD_HEIGHT,
  DEFAULT_HARDBOARD_PRICE_EUR,
  DEFAULT_HARDBOARD_THICKNESS,
  EDGE_PRICE_MM2_EUR,
  EDGE_PRICE_MM05_EUR,
  CUTTING_MINUTES_PER_SHEET,
  EDGING_MINUTES_PER_SHEET,
  DOOR_CLEARANCE_TOP,
  DOOR_CLEARANCE_BOTTOM,
  DOOR_GAP_X,
  DOOR_SIDE_GAP_EACH,
  DRAWER_DOOR_GAP,
  DRAWER_RAIL_BELOW_FRONT,
  DEFAULT_DRAWER_FRONT_HEIGHT,
  MAX_DRAWERS,
  MAX_SHELVES,
  COMBINED_FRONT_SAW_BUFFER,
  ROLLER_SLIDE_SIDE_GAP,
  SOFT_SLIDE_SIDE_GAP,
  SOFT_SLIDE_OUTER_RAIL_SHORTEN,
  SOFT_INNER_RAIL_HEIGHT_DROP,
  DOOR_EDGE_MM,
  DOOR_EDGE_BOTH,
  sheetKind,
  partKind,
  normalizeSheet,
  usedBoardCostEur,
  billedSheetCount,
  edgeBandingCostEur,
  referenceSheet,
  firstSheetOfKind,
  doorCutSize,
  doorCutRuleNote,
  drawerFrontCutSize,
  doorWithDrawersCutSize,
  doorWithDrawerCutSize,
  drawerBoxRails,
  parseDoorCount,
  parseDrawerFrontHeights,
  parseShelfCount,
  hardboardCutSize,
  remainingFrontHeight,
  equalDrawerFrontHeights,
  drawerFrontsAreEven,
  canCombineFronts,
  combinedFrontCutHeight,
  boardKindLabel,
  createHardboardSheet,
} from './materials'
export type { BoardKind, DoorCount, DrawerBoxRails } from './materials'
export {
  addCabinetAndLabel,
  updateCabinetAndLabel,
  removeCabinetAndLabel,
  rebuildCabinets,
  type CabinetState,
} from './apply'
export { createDrawCam, Board, BETWEEN_FACES, SIDE_LEFT_BODY, SIDE_LEFT_TOP, SIDE_RIGHT, BOX_FACES } from './draw-3d'
export type { DrawCam, DrawFaces } from './draw-3d'
export {
  NIGHTSTAND_TYPE_ID,
  NIGHTSTAND_JOINERY,
  NIGHTSTAND_LEGS_JOINERY,
  DEFAULT_NIGHTSTAND_PARAMS,
  PLINTH_INSET,
  parseNightstandParams,
  measureNightstand,
  generateNightstand,
  nightstandType,
} from './nightstand'
export type { NightstandParams } from './nightstand'
export {
  SECTION_TYPE_ID,
  DEFAULT_SECTION_PARAMS,
  parseSectionParams,
  generateSection,
  sectionType,
} from './section'
export type { SectionParams } from './section'
export {
  WARDROBE_TYPE_ID,
  DEFAULT_WARDROBE_PARAMS,
  parseWardrobeParams,
  generateWardrobe,
  wardrobeType,
} from './wardrobe'
export type { WardrobeParams } from './wardrobe'
export {
  SLIDING_PARTITION_SETBACK_MM,
  SLIDING_SHELF_FROM_PARTITION_MM,
  SLIDING_DOOR_OVERLAP_MM,
  SLIDING_BOTTOM_TRACK_MM,
  SLIDING_DRAWER_FROM_BOTTOM_MM,
  SLIDING_HANDLE_PROFILE_MM,
  SLIDING_CAP_PROFILE_MM,
  parseDoorStyle,
  parseSlidingEdges,
  defaultSlidingEdges,
  centerSlidingPartition,
  layoutSlidingDoors,
  slidingEdgeLabel,
  slidingProfileMm,
} from './sliding-doors'
export type { DoorStyle, SlidingEdgeKind, SlidingDoorEdges, SlidingDoorLeaf } from './sliding-doors'
export type { CabinetPartColors, CabinetPartColorKey } from './colors'
export {
  DEFAULT_PART_COLORS,
  DEFAULT_WOOD_COLOR,
  DEFAULT_LEG_COLOR,
  DEFAULT_HARDBOARD_COLOR,
  PART_COLOR_FIELDS,
  parsePartColors,
  partFaces,
} from './colors'
